### ISSUE TITLE
support environment vars that take values from secrets using `secretKeyRef:`

### ISSUE THREAD

**Issue by erikerlandson** [vpavlin/jupyterhub-singleuser-profiles#12]
Concept would be to modify the spawner to handle more advanced env-var structures, like:
```yaml
    - env:
      - name: MYAPP_SECRET_TOKEN
        valueFrom:
          secretKeyRef:
            key: SECRET_TOKEN
            name: secret-token-for-my-app
```
see for example:
https://major.io/2018/12/06/use-secret-as-environment-variable-in-openshift-deployments/

**Comment by erikerlandson** [comment]
possible generalization, might be allowing "arbitrary" yaml injection onto the jupyter pod, or the container inside

**Comment by vpavlin** [comment]
I am not a big fan of free form injecting into resources, although in the JH context it is probably ok, because only "admins" should have access to the deployment.

The env var mapping is definitely great idea and we should do that

**Comment by erikerlandson** [comment]
agreed, arbitrary injection is a chainsaw, and out of scope on this in any case

**Comment by erikerlandson** [comment]
also configmap variation:
```yaml
      env:
        - name: MY_CONFIGMAP_VALUE
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: mykey
```
